name: Google Review Tracker

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test Secret
        env:
          APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
        run: python tracker.py
